# Configuration file for GeoPressureR parameters
#
# This file stores all the parameters used by the GeoPressureR functions, following the best
# practice to separate parameters from codes. This file is used with the config R package
# <https://rstudio.github.io/config/> which allows to retrieve the value of each parameter
# in your analysis files.
#
# This file is meant to be adapted based on your needs: feel free to add or remove parameters either
# in the default or for each tag. It is recommended to specify all parameters used, even if you
# use the default value.
#
# You can check the documentation of each function to learn what each of these parameters are doing
# as well as checking in 4-geopressure.R

default:
  tag_create: # ?tag_create()
    # crop_start: NULL # Generally set at the tag level
    # crop_end: NULL
  tag_set_map: # ?tag_set_map()
    extent: [-5, 40, -30, 50] # [W, E, S, N]
    scale: 5 # 1 (min) -> 1째 ; 2 -> 0.5째 ; 5 -> 0.25째 ; 10 (max) -> 0.1째
    include_stap_id: NULL # default, take all
    include_min_duration: 0 # in hours
  geopressure_map: # ?geopressure_map()
    max_sample: 250
    margin: 20 # in m
    sd: 1
    thr_mask: 0.9
    log_linear_pooling_weight: !expr \(n) log(n)/n
  twilight_create: # ?twilight_create()
    # twl_thr: NULL
    # twl_offset: NULL # in hours
  geolight_map: # ?geolight_map()
    twl_calib_adjust: 1.4
    twl_llp: !expr \(n) log(n)/n
  graph_create: # ?graph_create()
    thr_likelihood: 0.99
    thr_gs: 150 # km/h
    # likelihood: NULL # Best to leave NULL.
  graph_add_wind:
    thr_as: 90 # km/h
  graph_set_movement: # ?graph_set_movement()
    # type: "gs"
    # method: "gamma"
    # shape: 7 # only for gamma
    # scale: 7
    # location: 40 # only for logistic
    # low_speed_fix: 15 # km/h
  graph_simulation: # ?graph_simulation()
    nj: 10
  pressurepath_create: # ?pressurepath_create()
    variable: ["altitude", "surface_pressure"]
    # solar_dep: 0
  geopressuretemplate: # ?geopressuretemplate()
    likelihood: ["map_pressure", "map_light"] #  for nothing
    outputs: ["marginal", "most_likely", "simulation"]
    pressurepath: ["most_likely"] # "geopressureviz"
  geomag_map:
    calib_data: "auto"
    calib_method: "sphere"

# Great Reed Warbler (32)  "#FF7F50", "#FF4500"
14TS:
  tag_create:
    crop_start: "2016-06-20"
    crop_end: "2017-05-01"
  tag_set_map:
    extent: [-5, 40, -30, 50]
    known:
      stap_id: [1] # -1 -> last stap
      known_lon: 27.7
      known_lat: 45.3
  bird_create:
    scientific_name: "Acrocephalus arundinaceus"
  color: "#FF6347"
  tag_mag:
    calib_data: "magCalib"

# Hoopoe (21)
16AJ:
  id: "16AJ"
  scientific_name: "Upupa epops"
  color: "#4682B4"
  calib_data: "outlier"
  extent: !expr c(-20, 30, -30, 50)
  include_min_duration: 24
  known: !expr data.frame(
    known_lat = 46.253,
    known_lon = 7.435,
    stap_id = 1)
  crop_start: "2016-07-15"
  crop_end: "2017-06-03"
16BY:
  id: "16BY"
  scientific_name: "Upupa epops"
  color: "#5F9EA0"
  calib_data: "outlier" # ok, but Not very good.
  extent: !expr c(-20, 30, -30, 50)
  include_min_duration: 24
  crop_start: "2016-06-15"
  crop_end: "2017-04-06"
  mag_axis: "backward-right-up"
16EG:
  id: "16EG"
  calib_data: "magCalib"
  color:  "#6495ED"
  scientific_name: "Upupa epops"
  extent: !expr c(-20, 30, -30, 50)
  include_min_duration: 24
  crop_start: "2016-07-15"
  crop_end: "2017-05-25"

# Bee-eaters (60) "#2E8B57"
14OI:
  scientific_name: "Merops apiaster"
  tag_create:
    crop_start: "2015-08-09"
    crop_end: "2016-07-11"
  tag_set_map: # ?tag_set_map()
    extent: [-5, 25, -10, 55] # [W, E, S, N]
    scale: 5
    known:
      stap_id: [1, 2, 3] # -1 -> last stap
      start: ["2015-08-09 00:00", "2015-10-04 12:00", "2016-05-20 12:00"]
      end: ["2015-08-31 12:00", "2016-03-30 12:00", "2016-07-11 00:00"]
      known_lon: [11.93128, null, 11.93128]
      known_lat: [51.3629, null, 51.3629]

# Alpine Swift (342)
12GE:
  scientific_name: "Tachymarptis melba"
  tag_create:
    crop_start: "2014-07-04"
    crop_end: "2015-06-10"
  tag_set_map:
    extent: [5, 50, -10, 50]
    scale: 2
    known:
      stap_id: [1, 2, 3, 4]
      start: ["2014-07-04 00:00", "2014-10-06 12:00", "2014-12-04 12:00","2015-04-07 12:00"]
      end: ["2014-10-1 12:00", "2014-11-30 12:00", "2015-03-30 12:00", "2015-06-10 00:00"]
      known_lon: [23.4, null, null, 23.4]
      known_lat: [42.7, null, null, 42.7]

# Other species with mag, but no calibration
# Turdus torquatus (4-5)
# Cossypha natalensis (7)
# Halcyon senegaloides (10)
# Anthus campestris (1)
